# Generated by Django 5.1.6 on 2025-02-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='Unknown User', max_length=100, unique=True),
        ),
    ]
